/* eslint-disable */
/** Auto-generated by scripts/scrape-pacha-artist-images.mjs — do not edit by hand. */
export type PachaArtistImageRow = { name: string; slug: string; image: string }

export const PACHA_ARTIST_IMAGE_ROWS: PachaArtistImageRow[] = [
  {
    "name": "2ManyDjs",
    "slug": "2manydjs",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/2manydjs.jpg"
  },
  {
    "name": "A-Trak",
    "slug": "trak",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/trak.jpg"
  },
  {
    "name": "Abracadabra",
    "slug": "blondish-presents-abracadabra",
    "image": "56445"
  },
  {
    "name": "Abril Love",
    "slug": "abril-love",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/31cfdb60-5320-4726-83cc-3d065e8b50d3/b3803c57-5f1b-4193-8dca-74b00b6d8132.jpg"
  },
  {
    "name": "Adam Ten",
    "slug": "adam-ten",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/adam-ten.jpg"
  },
  {
    "name": "Adriatique",
    "slug": "adriatique",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/adriatique.jpg"
  },
  {
    "name": "Ahmed Spins",
    "slug": "ahmed-spins",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/ahmed-spins.jpg"
  },
  {
    "name": "AJ Christou",
    "slug": "aj-christou",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/31b0af9f-48df-49a3-9d13-cbcfc9fd5d52/4e6312b3-ca35-47b1-a185-7ca535a8b1f7.webp"
  },
  {
    "name": "Ajna",
    "slug": "ajna",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/ajna.jpg"
  },
  {
    "name": "Ale De Tuglie",
    "slug": "ale-de-tuglie",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/ale-de-tuglie.jpg"
  },
  {
    "name": "Alex Wann",
    "slug": "alex-wann",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/alex-wann.jpg"
  },
  {
    "name": "Alexandria",
    "slug": "alexandria",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/caeb1e7d-2de7-40af-a545-ff2418913e4a/0137135e-6c3c-4174-83d8-3db4bab1afd9.jpg"
  },
  {
    "name": "Alle Farben",
    "slug": "alle-farben",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/alle-farben.jpg"
  },
  {
    "name": "Amê (DJ Set)",
    "slug": "ame-dj-set",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/ame-dj-set.jpg"
  },
  {
    "name": "AMÉMÉ",
    "slug": "ameme",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/ameme.jpg"
  },
  {
    "name": "Anané",
    "slug": "anane",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/anane.jpg"
  },
  {
    "name": "Anil Aras",
    "slug": "anil-aras",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/f0023fa5-e3cf-400a-9b45-1ff25a7924e8/fb8f4cda-7c70-4f47-8c6d-35816cfc88db.jpg"
  },
  {
    "name": "Anna Tur",
    "slug": "anna-tur",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/anna-tur.jpg"
  },
  {
    "name": "ANOTR",
    "slug": "anotr",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/Artists/ANOTR.jpg"
  },
  {
    "name": "Anthony Barrios",
    "slug": "anthony-barrios",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/b75ba543-f3f1-425f-a0ae-2756eb658fc3/8821d51b-954b-4893-8eae-242ec28df4c1.jpg"
  },
  {
    "name": "Antonio Pica",
    "slug": "antonio-pica",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/67fb8cbf-582d-42d1-a197-b5082fe5e33d/561ada10-4581-4a94-b483-525aa77a2f5a.jpg"
  },
  {
    "name": "Anyma",
    "slug": "anyma",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/anyma.jpg"
  },
  {
    "name": "Apache",
    "slug": "apache",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/apache.jpg"
  },
  {
    "name": "AR/CO",
    "slug": "ar-co",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/a85d578d-a51d-4191-a541-745fec969e29/d56914b5-89c0-4c51-a8fb-da0deda6fb88.jpeg"
  },
  {
    "name": "Arapu",
    "slug": "arapu",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/daf26054-d75e-4984-b07b-8de9ea39a82c/b5ef3a92-b247-4fc5-9668-6c52338a2ca6.jpg"
  },
  {
    "name": "Arielle Free",
    "slug": "arielle-free",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/arielle-free.jpg"
  },
  {
    "name": "Armand Van Helden",
    "slug": "armand-van-helden",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/armand-van-helden.jpg"
  },
  {
    "name": "ARODES",
    "slug": "arodes",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/0d3c1d04-13db-44ed-8554-b9f58a60a60e/6f1f4aaf-7e20-45c4-ab75-a1a6a67ba4cb.webp"
  },
  {
    "name": "Avangart Tabldot",
    "slug": "avangart-tabldot",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/avangart-tabldot.jpg"
  },
  {
    "name": "Baggi",
    "slug": "baggi",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/75596880-37de-4d14-ab5d-23070ce96cf3/d8aa126a-5b5f-4535-a835-5546d0118ac5.jpg"
  },
  {
    "name": "Barry Can´t Swim",
    "slug": "barry-cant-swim",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/barry-cant-swim.jpg"
  },
  {
    "name": "Ben Sterling",
    "slug": "ben-sterling",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/ben-sterling.jpg"
  },
  {
    "name": "Black Coffee",
    "slug": "black-coffee",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/black-coffee.jpg"
  },
  {
    "name": "BLOND:ISH",
    "slug": "blondish",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/blondish.jpg"
  },
  {
    "name": "Blu DeTiger",
    "slug": "blu-detiger",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/4fb4edda-2c6d-4482-af92-cfd36c016c5a/cd049738-2e73-4d11-aad0-4425181cf243.jpg"
  },
  {
    "name": "Boys Noize",
    "slug": "boys-noize",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/0b9441a9-9cb6-4aa3-b298-fc438f63c4d2/8f581644-d1aa-4bca-9b1a-dbed41dfec70.webp"
  },
  {
    "name": "Breakbot",
    "slug": "breakbot",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/02733199-44f1-4747-b1c4-65b6573d0070/45a3455d-617d-4c04-a642-ea817176b2d8.webp"
  },
  {
    "name": "Broken Hill",
    "slug": "broken-hill",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/9554aefd-37c1-47d5-9df9-b94682a78081/7ea839fc-2a03-4023-bd37-524e230b3755.webp"
  },
  {
    "name": "Brothers Macklovitch",
    "slug": "brothers-macklovitch",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/738f4e80-2ad1-473c-9073-1cd9ffc66ad9/dd3dd043-66de-4e48-9be4-7c7f49d315fd.webp"
  },
  {
    "name": "Brunello",
    "slug": "brunello",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/4d54c706-66da-44a6-9bae-d335048d98f5/7634d895-5450-4b80-ae25-c6afa0ba92b5.jpg"
  },
  {
    "name": "Busy P",
    "slug": "busy-p",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/5e87629b-d48d-4021-9b08-dbb5cf3f78b6/00c78098-9d0e-48f9-ab10-ed00784cd8b5.jpeg"
  },
  {
    "name": "Calvin Clarke",
    "slug": "calvin-clarke",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/calvin-clarke.jpg"
  },
  {
    "name": "Camila Jun",
    "slug": "camila-jun",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/camila-jun.jpg"
  },
  {
    "name": "Carlita",
    "slug": "carlita",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/carlita.jpg"
  },
  {
    "name": "CC:DISCO!",
    "slug": "cc-disco",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/92acde80-3f64-4187-88d8-c074037a424b/111582a8-07c0-4ef2-9ba9-f27d7c310284.jpeg"
  },
  {
    "name": "Cerrone",
    "slug": "cerrone",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/cd0af609-afc1-452c-8ea6-ee4b67c3fe57/5c5c0e4f-c964-4dc1-86b8-4f5535ca0787.jpg"
  },
  {
    "name": "Chapa Castelo",
    "slug": "chapa-castelo",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/38815b61-699d-4741-bd4f-700ef9a0ef1a/61e3db21-7339-4b1c-9419-4412fff0caf2.jpeg"
  },
  {
    "name": "Chelina Manuhutu",
    "slug": "chelina-manuhutu",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/chelina-manuhutu.jpg"
  },
  {
    "name": "Chinonegro",
    "slug": "chinonegro",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/4c4045ef-27a3-461c-87a0-28b75919f126/07df5dca-b972-4a27-a1be-f54e4917a030.jpg"
  },
  {
    "name": "Chloé Caillet",
    "slug": "chloe-caillet",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/chloe-caillet.jpg"
  },
  {
    "name": "Chris Stussy",
    "slug": "chris-stussy",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/chris-stussy.jpg"
  },
  {
    "name": "Cloonee",
    "slug": "cloonee",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/cloonee.jpg"
  },
  {
    "name": "Cuky",
    "slug": "cuky",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/cc819bfd-8ea3-47a7-ac3c-a6a5875f5bcf/1e5f7138-eea4-4f35-8eef-9afaaa668536.jpg"
  },
  {
    "name": "Culoe De Song",
    "slug": "culoe-de-song",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/63a9dc33-9406-41d2-81e5-98a4e3f200cd/1608f9cb-8762-4a39-bea9-396a79a5d0ae.webp"
  },
  {
    "name": "CYRIL",
    "slug": "cyril",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/ea8df642-f1d0-4903-ae01-e9b60d35c98d/eb987374-4a8d-4eaf-b01a-2f4fd0575875.png"
  },
  {
    "name": "D.O.D",
    "slug": "dod",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/c455cc7b-ef67-4fc9-a700-94a78b103fec/39df48e3-b696-4692-85b1-3add22b2328e.jpg"
  },
  {
    "name": "Da Vid",
    "slug": "da-vid",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/da-vid.jpg"
  },
  {
    "name": "Damian Lazarus",
    "slug": "damian-lazarus",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/40065cd2-4985-448b-9d54-dacee31f52df/21a90ae0-dc61-48da-aecc-80a0d5038460.jpeg"
  },
  {
    "name": "Danny Howard",
    "slug": "danny-howard",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/danny-howard.jpg"
  },
  {
    "name": "Danyelino",
    "slug": "danyelino",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/064d16a4-694c-4c77-94a6-5127baa81417/4b30aa0f-1305-45d4-ab48-962baeb91ea7.jpeg"
  },
  {
    "name": "Darco",
    "slug": "darco",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/134a75c5-56c3-471b-97dd-c148a47691c0/8bb94ae6-e4e0-4dee-97b3-a791e24bf59f.jpeg"
  },
  {
    "name": "Darque",
    "slug": "darque",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/137236cb-9f4a-46a2-977e-3247da81f827/d3878540-f330-4063-a769-6f89074df07f.webp"
  },
  {
    "name": "David Bay",
    "slug": "david-bay",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/david-bay.jpg"
  },
  {
    "name": "David Morales",
    "slug": "david-morales",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/david-morales.jpg"
  },
  {
    "name": "Davide Squillace",
    "slug": "davide-squillace",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/davide-squillace.jpg"
  },
  {
    "name": "DEDRO",
    "slug": "dedro",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/d9c19765-1363-4e4f-be06-2625105aef31/c76bedd7-065c-44c8-9610-4722e545edb4.jpeg"
  },
  {
    "name": "Deer Jade",
    "slug": "deer-jade",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/deer-jade.jpg"
  },
  {
    "name": "Denis Sulta",
    "slug": "denis-sulta",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/denis-sulta.jpg"
  },
  {
    "name": "Dennis Cruz",
    "slug": "dennis-cruz",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/dennis-cruz.jpg"
  },
  {
    "name": "Dennis Ferrer",
    "slug": "dennis-ferrer",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/dennis-ferrer.jpg"
  },
  {
    "name": "Derrick McKenzie",
    "slug": "derrick-mckenzie",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/8df27a56-e442-426e-bbd6-4e6af6299d03/b71b2854-7699-40cc-a0b1-525adf79defe.webp"
  },
  {
    "name": "DESIREE",
    "slug": "desiree",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/fb1c6872-de60-4e0a-84dd-88bfc2919bff/08e83788-5619-4048-9b49-cf8d51a1ad60.jpeg"
  },
  {
    "name": "DiOSA",
    "slug": "diosa",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/d1e640e9-7159-4637-8e5a-026bb22994d0/b4994cb8-616b-4360-a90f-8886db2eed6e.jpg"
  },
  {
    "name": "Diplo",
    "slug": "diplo",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/diplo.jpg"
  },
  {
    "name": "Discip",
    "slug": "discip",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/discip.jpg"
  },
  {
    "name": "DISCIPLES",
    "slug": "Disciples",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/ba5af69e-be36-4cdc-b9b2-d7e018bd9b87/81fc0f96-6db9-49f1-bf66-4abcb667451d.png"
  },
  {
    "name": "Disclosure",
    "slug": "disclosure",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/68bc1f7d-4f86-438d-aeb5-3a962dbb0021/46e2435a-53ad-4ba9-8963-20303cb6bcf1.jpg"
  },
  {
    "name": "Disco Dom",
    "slug": "disco-dom",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/077011d4-7640-4009-9182-abe979a44300/1ca18370-e5bd-4d3e-9b04-eecfade5c0e8.jpeg"
  },
  {
    "name": "Dixon",
    "slug": "dixon",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/0fb554b9-73a6-426d-9c91-d69dc73eae96/36e9fa3f-0f1f-4290-875a-a94c70af3d13.jpeg"
  },
  {
    "name": "DJ Gigola",
    "slug": "dj-gigola",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/dj-gigola.jpg"
  },
  {
    "name": "DJ Tennis",
    "slug": "dj-tennis",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/e94f7262-d42c-4c65-b145-4610c79a3f83/01fb3aed-dcfc-4c4f-adb4-93f67191b5f6.jpg"
  },
  {
    "name": "Dombresky",
    "slug": "dombresky",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/dombresky.jpg"
  },
  {
    "name": "Doozie",
    "slug": "doozie",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/c7183e82-761f-41d3-99fc-3d2129138403/e9b88bd7-4843-439a-bef7-880380849b46.webp"
  },
  {
    "name": "East End Dubs",
    "slug": "east-end-dubs",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/east-end-dubs.jpg"
  },
  {
    "name": "Easttown",
    "slug": "easttown",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/2a0e11b3-d363-4dc2-8ac4-822c0845f19f/2f0b2622-e420-4dd0-bd51-59678815ac68.jpg"
  },
  {
    "name": "Eats Everything",
    "slug": "eats-everything",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/eats-everything.jpg"
  },
  {
    "name": "EDX",
    "slug": "edx",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/edx.jpg"
  },
  {
    "name": "Enzo Siragusa",
    "slug": "enzo-siragusa",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/57866506-0138-4d25-96ae-decff98a3e9b/432c9692-c79e-4a7a-9167-bd0deb6f132c.jpg"
  },
  {
    "name": "Eric Prydz",
    "slug": "eric-prydz",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/1ef06ac0-7403-4a4a-8a75-69487ee6517e/b0f7b186-0da0-4410-a74b-01e21bba562c.jpg"
  },
  {
    "name": "Fatboy Slim",
    "slug": "fatboy-slim",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/fatboy-slim.jpg"
  },
  {
    "name": "Fletch",
    "slug": "fletch",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/fletch.jpg"
  },
  {
    "name": "Fleur Shore",
    "slug": "fleur-shore",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/fleur-shore.png"
  },
  {
    "name": "Flight Facilities",
    "slug": "flight-facilities",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/flight-facilities.jpg"
  },
  {
    "name": "Flower Power",
    "slug": "roger-sanchez-flower-power",
    "image": "68df91d4ed302a7ec51aa51f"
  },
  {
    "name": "Franc Fala",
    "slug": "franc-fala",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/c9bee332-f937-4e6d-8faf-81aea1336bc6/a1cf651c-792b-440d-9e9b-a0592efd2786.webp"
  },
  {
    "name": "Frank Storm",
    "slug": "frank-storm",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/frank-storm.png"
  },
  {
    "name": "Franky Rizardo",
    "slug": "franky-rizardo",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/franky-rizardo.jpg"
  },
  {
    "name": "Franky Wah",
    "slug": "franky-wah",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/4aaf48b0-56cb-4955-adc6-bcb8048543ef/d84ee07f-36ef-4b0e-a4ef-f657dee27a8a.avif"
  },
  {
    "name": "Gala",
    "slug": "gala",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/6b81a602-2992-4d05-a801-04f2d7882063/fa28670e-6484-4a71-9e77-0be6ccd5034a.jpeg"
  },
  {
    "name": "Gennaro",
    "slug": "gennaro",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/3fca0879-9df1-4217-9c06-454cd0a1a3f8/5829841a-ad6d-4ace-8e3d-2612810592f5.webp"
  },
  {
    "name": "Gerd Janson",
    "slug": "gerd-janson",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/gerd-janson.jpg"
  },
  {
    "name": "GORDO",
    "slug": "gordo",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/gordo.jpg"
  },
  {
    "name": "Grace Arribas",
    "slug": "Grace-Arribas",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/31626ebe-85f4-4e2c-ac5e-562b94ee744f/64d0e44b-5943-4c08-8ed7-b7cd6cc18be2.webp"
  },
  {
    "name": "Gustavo Domínguez",
    "slug": "gustavo-dominguez",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/18c21a30-9985-4eee-98f3-20e353172f68/f08b7999-8e5c-4e0c-a7de-aa065d785c97.jpg"
  },
  {
    "name": "HAAi",
    "slug": "haai",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/haai.jpg"
  },
  {
    "name": "Hank",
    "slug": "hank",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/hank.jpg"
  },
  {
    "name": "Harvy Valencia",
    "slug": "harvy-valencia",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/9f7e8e7c-d99e-43bb-8d90-bc185553bc55/7d75161c-3947-4ab2-9912-d59aa92b2805.jpeg"
  },
  {
    "name": "Henrik Schwarz",
    "slug": "henrik-schwarz",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/0f3ab885-1620-49a3-8620-62db4bb47574/e6ee4da4-38af-4053-a722-a5e04368a4fa.jpeg"
  },
  {
    "name": "HoneyLuv",
    "slug": "honeyluv",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/honeyluv.jpg"
  },
  {
    "name": "Hot Since 82",
    "slug": "hot-82",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/hot-82.jpg"
  },
  {
    "name": "Icona Pop",
    "slug": "icona-pop",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/icona-pop.jpg"
  },
  {
    "name": "Idris Elba",
    "slug": "idris-elba",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/5a88f567-c032-41c9-b1c9-dec7000a9fdf/bf1f4177-0836-4e8f-92bf-3ff2328f45a9.jpeg"
  },
  {
    "name": "Idriss D",
    "slug": "idriss-d",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/ee83d9e4-6418-4882-9cd2-b80333bd2b2a/1700929a-36c6-4f50-87bd-e4438836f75c.jpg"
  },
  {
    "name": "II Faces",
    "slug": "ii-faces",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/ii-faces.jpg"
  },
  {
    "name": "Ilario Alicante",
    "slug": "ilario-alicante",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/ilario-alicante.jpg"
  },
  {
    "name": "JACKSON",
    "slug": "jackson",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/06e74331-ad4b-43a1-901d-56b801458cf6/0acf4b96-01bc-4705-95b0-4d02660c81a2.webp"
  },
  {
    "name": "Jaden Bojsen",
    "slug": "jaden-bojsen",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/95721bfb-4038-4421-961d-3ea42d992a37/fa332087-1c66-42f0-8df3-0859d51d0579.jpg"
  },
  {
    "name": "Jamie Jones",
    "slug": "jamie-jones",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/jamie-jones.jpg"
  },
  {
    "name": "Jamie xx",
    "slug": "jamie-xx",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/jamie-xx.jpg"
  },
  {
    "name": "Jan Blomqvist",
    "slug": "jan-blomqvist",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/jan-blomqvist.jpg"
  },
  {
    "name": "Jax Jones",
    "slug": "jax-jones",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/fde07b14-43c3-45a2-a17e-3fff29ba8c31/6f0ead9e-3a06-48ca-94aa-5e9f51fb0d19.jpg"
  },
  {
    "name": "Jayda G",
    "slug": "jayda-g",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/jayda-g.jpg"
  },
  {
    "name": "Jazzy",
    "slug": "jazzy",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/jazzy.jpg"
  },
  {
    "name": "Jean Pierre",
    "slug": "jean-pierre",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/jean-pierre.jpg"
  },
  {
    "name": "Jesse Calosso",
    "slug": "jesse-calosso",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/jesse-calosso.jpg"
  },
  {
    "name": "Jessica Brankka",
    "slug": "jessica-brankka",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/jessica-brankka.jpg"
  },
  {
    "name": "Jimi Jules",
    "slug": "jimi-jules",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/79ab1fb0-96bf-47a4-90ee-a515b6b117af/27f99416-da71-4f26-a4b6-480de71edbdb.jpg"
  },
  {
    "name": "Jodie Harsh",
    "slug": "jodie-harsh",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/jodie-harsh.jpg"
  },
  {
    "name": "Joey Daniel",
    "slug": "joey-daniel",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/joey-daniel.jpg"
  },
  {
    "name": "JØRD",
    "slug": "jord",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/82ba2673-1af8-4077-9ac9-bb06f203244b/6ae53ce0-e8c7-48f9-ac35-d85e42fe84ed.webp"
  },
  {
    "name": "Joseph Capriati",
    "slug": "joseph-capriati",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/joseph-capriati.jpg"
  },
  {
    "name": "Joss Dean",
    "slug": "joss-dean",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/38ee5a05-93dc-4289-8e9b-df5b27d0cb48/2bbaaeaf-066e-4d24-8b8c-2391d8a13494.jpeg"
  },
  {
    "name": "Julya Karma",
    "slug": "julya-karma",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/3b41503c-d81a-459f-ae67-ec39ac3ac6c8/792386af-f2ca-44c3-8e8e-bb4410883e21.webp"
  },
  {
    "name": "Karen Harding",
    "slug": "karen-harding",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/a7fa3042-bdb6-42b9-850e-1efcc1a0b348/04e07555-55c1-42ba-89cd-5f8ca59cdaa0.jpeg"
  },
  {
    "name": "Karretero",
    "slug": "karretero",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/2893e724-9b0c-4c35-b6c7-dc4231eddcaa/cbf71d7d-cace-412e-8796-347c7ca89af1.jpg"
  },
  {
    "name": "Kasango",
    "slug": "kasango",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/09746d82-4238-4747-8a31-517e390536ef/63d76391-714f-4e00-8fbe-3eb9ceeb4fc3.webp"
  },
  {
    "name": "KAYTRANADA",
    "slug": "kaytranada",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/595d57dd-30ce-4e5b-b1c1-71204bafefc3/ee433cea-d61a-42fa-8822-250d6bcfd1d8.jpeg"
  },
  {
    "name": "Kaz James",
    "slug": "kaz-james",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/kaz-james.jpg"
  },
  {
    "name": "Kenny Dope",
    "slug": "kenny-dope",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/kenny-dope.jpg"
  },
  {
    "name": "Kerri Chandler",
    "slug": "kerri-chandler",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/kerri-chandler.jpg"
  },
  {
    "name": "KETTAMA",
    "slug": "kettama",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/4f6c86b1-9925-4e79-b113-7e6a0cb71c1a/4a68353b-eae3-4b73-ad26-b1bbb4273375.webp"
  },
  {
    "name": "Kevin Brauer",
    "slug": "kevin-brauer",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/2ca19683-2b0c-47e4-9aa4-afb3b155ee23/6134a5c5-a9df-46cb-afc1-d62817b6eb55.jpg"
  },
  {
    "name": "Kilimanjaro",
    "slug": "kilimanjaro",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/kilimanjaro.jpg"
  },
  {
    "name": "Kimonos",
    "slug": "kimonos",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/kimonos.jpg"
  },
  {
    "name": "Kitty Amor",
    "slug": "kitty-amor",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/21a07d58-0959-47ac-abd0-5483c64f7d19/ad7a90b5-6ffe-4905-a9df-71656351b588.jpg"
  },
  {
    "name": "Kitty Ca$h",
    "slug": "kitty-cash",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/c4db9579-7ed0-4b52-8200-eefc398dbacf/e14280b4-db5c-4fe5-9a0c-76cff7151c39.webp"
  },
  {
    "name": "KOKO",
    "slug": "koko",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/2ad937cb-0e67-41ae-abd8-39926cef5b31/5db4fdce-d0a0-4f16-ab8c-8867eed24eba.png"
  },
  {
    "name": "Kristen Knight",
    "slug": "kristen-knight",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/9942e4aa-1156-4b83-b8f4-724bb29566a1/947d191b-5d67-436c-9c44-71c047bba267.jpg"
  },
  {
    "name": "Kungs",
    "slug": "kungs",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/kungs.jpg"
  },
  {
    "name": "LAEET",
    "slug": "laeet",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/43e136f1-10e5-4a52-ae4f-86a2bb2ec992/5b2da895-bfba-4db7-83df-1e75b061788d.jpg"
  },
  {
    "name": "Leon",
    "slug": "leon",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/ef2c0cc6-defe-44ef-9ece-a1ac94757fa3/01d0e448-2909-4048-85ff-8897a1b000a7.webp"
  },
  {
    "name": "Locky",
    "slug": "locky",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/65847991-54ae-47ac-8b1c-047952747e33/ff553b92-d8f4-45f7-b822-7502cf41efbf.jpg"
  },
  {
    "name": "Loco Dice",
    "slug": "loco-dice",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/loco-dice.jpg"
  },
  {
    "name": "Lost Frequencies",
    "slug": "lost-frequencies",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/496ecf0f-1d48-46ee-8965-2e16117e6aa9/e0235aa7-3178-4b8c-895c-87b47f00b3d2.png"
  },
  {
    "name": "Louie Vega",
    "slug": "louie-vega",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/555c91c6-5ed8-466d-a540-94e71faf6f63/f82ed4c7-0d39-449c-8323-79efb412b3d1.jpg"
  },
  {
    "name": "Lovra",
    "slug": "lovra",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/lovra.jpg"
  },
  {
    "name": "Low Steppa",
    "slug": "low-steppa",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/low-steppa.jpg"
  },
  {
    "name": "LP Giobbi",
    "slug": "lp-giobbi",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/lp-giobbi.jpg"
  },
  {
    "name": "Luciano",
    "slug": "luciano",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/luciano.jpg"
  },
  {
    "name": "Luke Dean",
    "slug": "luke-dean",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/33634158-c066-4565-9b25-4c5dd1e52079/3a68e0be-13e3-45f9-bcea-f8a2c947c181.jpg"
  },
  {
    "name": "Mahmut Orhan",
    "slug": "mahmut-orhan",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/85b6ec87-891a-4200-8fbb-77d80512012c/de72988f-c65c-46bf-8fc0-955b96fecba1.jpg"
  },
  {
    "name": "Mahony",
    "slug": "mahony",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/mahony.jpg"
  },
  {
    "name": "Malóne Morez",
    "slug": "malone-morez",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/16e8c533-d5e1-4aee-b9e3-05f8c0c34180/544e4793-84ff-4d5d-be12-d297aebf7a36.webp"
  },
  {
    "name": "Manda Moor",
    "slug": "manda-moor",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/manda-moor.jpg"
  },
  {
    "name": "Marco Carola",
    "slug": "marco-carola",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/marco-carola.png"
  },
  {
    "name": "Marco Tropeano",
    "slug": "marco-tropeano",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/b60535a7-a22b-49a6-91c3-a469fa137d19/77091d95-a721-467d-b6c0-2fffc49ad9cf.jpg"
  },
  {
    "name": "Mark Knight",
    "slug": "mark-knight",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/cd6d2493-4f79-4a6f-91f2-1bf72a495d19/1129456a-417d-423e-9598-be49ddfac0f2.jpg"
  },
  {
    "name": "Marsolo",
    "slug": "marsolo",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/c3fa5153-3724-433e-bb6e-f83b4d6aa914/db33672a-1e90-46f0-b0c6-2e59d50a7ee9.webp"
  },
  {
    "name": "Marten Hørger",
    "slug": "marten-horger",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/3ba70553-4c6a-4783-862b-b5440ab38085/a4ed0973-2eb3-4098-9179-10804c5774bd.jpg"
  },
  {
    "name": "Marten Lou",
    "slug": "marten-lou",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/9b5785fe-f7a4-4d27-a09e-52a273092021/90ecad8e-5bd7-4cc5-ba05-d19a80aae3f8.jpg"
  },
  {
    "name": "Mason Collective",
    "slug": "mason-collective",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/mason-collective.jpg"
  },
  {
    "name": "Mau P",
    "slug": "mau-p",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/mau-p.jpg"
  },
  {
    "name": "Max Dean",
    "slug": "max-dean",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/max-dean.jpg"
  },
  {
    "name": "Max Styler",
    "slug": "max-styler",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/859adcb9-8e1e-4b1f-bed1-bd6de7391ce5/7e4d493c-37c7-47d7-b05d-f6f29e8fad34.jpg"
  },
  {
    "name": "MEDNAS",
    "slug": "mednas",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/e7c117f9-0e3d-415e-83a9-0f75762f128b/f445e289-1d44-4314-ba61-97e231429925.jpeg"
  },
  {
    "name": "Melanie C",
    "slug": "melanie-c",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/melanie-c.jpg"
  },
  {
    "name": "Michael Bibi",
    "slug": "michael-bibi",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/michael-bibi.jpg"
  },
  {
    "name": "Midnight Generation",
    "slug": "midnight-generation",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/2f85d1d0-62e4-411f-824e-79e0132e6221/1921bea2-0cda-4334-a91d-cfd6f2f49528.webp"
  },
  {
    "name": "Mila-Rose",
    "slug": "mila-rose",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/28000519-9804-44f0-b057-e1be4ac9ce8d/4b0c1fab-06f5-4a9c-ac94-82279e4796a5.webp"
  },
  {
    "name": "MĪMĪ x FY",
    "slug": "mimi-fy",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/6cdb6c5a-b685-45ce-90c3-d71f9edf6901/bbc51643-38e8-4195-9fbe-728c895e01f6.webp"
  },
  {
    "name": "Minna",
    "slug": "minna",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/781d2682-446d-4600-933d-444979681d9d/ec90afe7-c08c-4d49-9bd4-ca1eba9e893a.webp"
  },
  {
    "name": "Mistajam",
    "slug": "mistajam",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/mistajam.jpg"
  },
  {
    "name": "Mita Gami",
    "slug": "mita-gami",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/b1c08dd4-0336-4279-b62f-eb49955c5506/b6facb21-d679-4120-bf41-2b099706da3d.jpg"
  },
  {
    "name": "Mochakk",
    "slug": "mochakk",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/mochakk.jpg"
  },
  {
    "name": "Monolink (Hybrid)",
    "slug": "monolink",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/monolink.jpg"
  },
  {
    "name": "Morgan Seatree",
    "slug": "Morgan-Seatree",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/Artists/Morgan+Seatree.webp"
  },
  {
    "name": "Moxie",
    "slug": "moxie",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/d9696c71-d740-49d0-8ff8-d6b76c7f94f9/f23d26c1-2361-44d2-b509-e8e194600814.jpg"
  },
  {
    "name": "Music On",
    "slug": "music-on",
    "image": "68df91a786feb0c2d1a2cd90"
  },
  {
    "name": "Myd",
    "slug": "myd",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/78357feb-c70b-4000-9fc4-3ef256e85df9/3a8d692a-62d2-438c-9cd5-ec9c4515d585.jpg"
  },
  {
    "name": "Nariman",
    "slug": "nariman",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/0ea1ff8c-1fdc-4be1-9ac0-9deb587d3122/16ee479f-79f9-4909-94e2-a11850baa351.jpg"
  },
  {
    "name": "Nervo",
    "slug": "nervo",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/nervo.jpg"
  },
  {
    "name": "Neverdogs",
    "slug": "neverdogs",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/neverdogs.jpg"
  },
  {
    "name": "Nic Fanciulli",
    "slug": "nic-fanciulli",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/nic-fanciulli.jpg"
  },
  {
    "name": "Nicky Jam",
    "slug": "nicky-jam",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/c85564f2-0368-4e87-bfb2-367738299451/d27e9d1e-afd9-4674-baa1-aaab69eba552.jpg"
  },
  {
    "name": "Nico Bernardini",
    "slug": "nico-bernardini",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/nicola-bernardini.jpg"
  },
  {
    "name": "Nicole Moudaber",
    "slug": "nicole-moudaber",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/b8881b14-0189-471d-b870-017f09eb54e2/c6c6157d-a975-431a-a1a4-5fba3b1fdbba.jpg"
  },
  {
    "name": "Noel Holler",
    "slug": "noel-holler",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/4cd64b0b-5ed6-4881-982a-bbe87d91fd37/a22cfa01-5c93-4d8a-b770-a3a5f57cd83b.jpg"
  },
  {
    "name": "Obskür",
    "slug": "obskur",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/46dea742-5efb-48fc-b6d4-1e022b7b7023/0e06168a-1e69-4eca-ba39-2aa906af1272.jpg"
  },
  {
    "name": "Olive F",
    "slug": "olive-f",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/olive-f.jpg"
  },
  {
    "name": "Oliver Heldens",
    "slug": "oliver-heldens",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/oliver-heldens.jpg"
  },
  {
    "name": "OMRI",
    "slug": "omri",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/2ecce3d7-7120-47fe-8099-9ff7a590f928/3d4097ee-fe7a-404e-b780-baa2fa72c018.jpg"
  },
  {
    "name": "Paco Osuna",
    "slug": "paco-osuna",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/paco-osuna.jpg"
  },
  {
    "name": "Parallelle",
    "slug": "parallelle",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/3914ba4d-b8b4-431a-8c6e-4872a8056eb3/712bc7f5-a7ca-492e-a7e2-fee97b2be712.jpeg"
  },
  {
    "name": "Patrick Topping",
    "slug": "patrick-topping",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/71fb05f5-a37b-4eec-8a65-7ec45c8cfafb/50d7c343-c4ea-4b2c-a0c3-ebd0bd241ebe.jpg"
  },
  {
    "name": "PAWSA",
    "slug": "pawsa",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/pawsa.jpg"
  },
  {
    "name": "Peace Control",
    "slug": "peace-control",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/0258a37e-4a0a-4554-bdd2-9e2c921e0990/56b81c18-fcaf-4351-a8a8-2e267116fb18.jpg"
  },
  {
    "name": "Peggy Gou",
    "slug": "peggy-gou",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/peggy-gou.jpg"
  },
  {
    "name": "Priku",
    "slug": "priku",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/1aa9dd87-0d22-4742-a9db-37ed3a4ae79f/2c5ab61b-b8b6-4c5c-b793-d51d5719bfbb.jpg"
  },
  {
    "name": "Prospa",
    "slug": "prospa",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/prospa.jpg"
  },
  {
    "name": "Prunk",
    "slug": "prunk",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/prunk.jpg"
  },
  {
    "name": "Purple Disco Machine",
    "slug": "purple-disco-machine",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/purple-disco-machine.jpg"
  },
  {
    "name": "Rafael",
    "slug": "rafael",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/e83f226c-5680-4d15-a6ac-b5c5451bd2f7/89744ce3-5a7f-4b6c-ae72-04542498d4e3.jpeg"
  },
  {
    "name": "Rampa",
    "slug": "Rampa",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/b1990744-863d-4441-91d2-baf0a0c11f06/c215a2f4-1cdf-4248-be12-f18bee4e35db.jpg"
  },
  {
    "name": "RICHE",
    "slug": "riche",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/c6330aa1-2f18-42aa-aaa4-56039cf7e201/6c510e2c-1408-4b6a-90ae-7713f31bd238.jpg"
  },
  {
    "name": "Rob the Bank",
    "slug": "rob-the-bank",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/ca67d9ac-83d3-469a-96e9-a9b85006b1d1/4fd65c58-1c3f-41ca-b6d7-445dd251055b.png"
  },
  {
    "name": "Robin Schulz",
    "slug": "robin-schulz",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/robin-schulz.jpg"
  },
  {
    "name": "Roger Sanchez",
    "slug": "roger-sanchez",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/roger-sanchez.jpg"
  },
  {
    "name": "Romy",
    "slug": "romy",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/5ef7f437-71cb-408d-92ca-46228396dcde/fc262ca4-5257-47ae-af92-86eca3e3ea4c.webp"
  },
  {
    "name": "Rooléh",
    "slug": "rooleh",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/dfcf714a-5d80-483c-a24e-aa135f9ed950/91d4be3d-ccad-4346-b22e-b70559be0c6a.jpg"
  },
  {
    "name": "Rosey Gold",
    "slug": "rosey-gold",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/9bbb442f-5ddf-4b66-9c9c-829523c08997/5abbcca0-f2a2-419d-bffa-4e168c5caf92.jpg"
  },
  {
    "name": "Rossi.",
    "slug": "rossi",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/rossi.jpg"
  },
  {
    "name": "RÜFÜS DU SOL [DJ Set]",
    "slug": "rufus-du-sol-dj-set",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/rufus-du-sol-dj-set.jpg"
  },
  {
    "name": "RY X",
    "slug": "ry-x",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/163e9f73-6409-4220-874f-7e5c1e58c3ce/e9bb6e0d-2ef8-4757-ba59-bf563125b46a.jpg"
  },
  {
    "name": "Sacchi",
    "slug": "sacchi",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/fe39d8f4-531b-4e02-a74b-c521d6be8980/8dcb7072-bdbb-4489-b89b-2b8cb62cfc35.webp"
  },
  {
    "name": "Saffron Stone",
    "slug": "saffron-stone",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/saffron-stone.jpg"
  },
  {
    "name": "Sally C",
    "slug": "sally-c",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/8d6cefdf-6cb8-44ef-b5bd-551a033c765b/627f6af4-d800-46ef-89c6-efd934242805.png"
  },
  {
    "name": "Salomé Le Chat",
    "slug": "salome-le-chat",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/salome-le-chat.jpg"
  },
  {
    "name": "Sam Divine",
    "slug": "sam-divine",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/sam-divine.jpg"
  },
  {
    "name": "Sam Oui",
    "slug": "sam-oui",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/281b7a9c-d762-45d2-b231-31f2b829173d/2710e106-3251-49d1-b90c-2592575a6f7d.jpg"
  },
  {
    "name": "Samantha Loveridge",
    "slug": "samantha-loveridge",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/samantha-loveridge.jpg"
  },
  {
    "name": "Samm",
    "slug": "samm",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/c3e5b485-3311-4204-b030-a3aa57ee6d89/3c540003-aa33-4395-a613-0ae926591228.jpeg"
  },
  {
    "name": "Sarah Story",
    "slug": "sarah-story",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/b57917c7-aa22-495d-bc45-04770d021124/44e5fc49-9822-4a0a-a0e6-cc6863a17ee7.jpg"
  },
  {
    "name": "Sergio Saffe",
    "slug": "sergio-saffe",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/f245f46f-dcd5-4852-b1c3-159b79620fe4/386cc651-5fe1-4613-a9e9-bf47bf28c05a.webp"
  },
  {
    "name": "Serve Cold",
    "slug": "serve-cold",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/bcaf6c07-e23c-4245-83eb-6fdd5f83ba57/d5bd1fe0-dd7f-4042-9d90-a279d471c830.webp"
  },
  {
    "name": "Seth Troxler",
    "slug": "seth-troxler",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/seth-troxler.jpg"
  },
  {
    "name": "SG Lewis",
    "slug": "sg-lewis",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/sg-lewis.jpg"
  },
  {
    "name": "Shanti Celeste",
    "slug": "shanti-celeste",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/b8600931-8809-4f87-bc0c-9003ea2f23d1/855bc9c7-d5d6-4d19-b0ae-1633f2bf2ee0.jpg"
  },
  {
    "name": "Shimza",
    "slug": "shimza",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/shimza.jpg"
  },
  {
    "name": "Siân Owen",
    "slug": "SIAN-OWEN",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/9ff1c58d-815f-4a1d-8b5a-cb3f60d09cc0/897e4ef9-5310-4d2d-9fdd-566f4c29d173.webp"
  },
  {
    "name": "Skrillex",
    "slug": "skrillex",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/skrillex.jpg"
  },
  {
    "name": "Solomun",
    "slug": "solomun",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/solomun.jpg"
  },
  {
    "name": "Solomun+1",
    "slug": "solomun",
    "image": "68df91b7e9db96a57d9c2795"
  },
  {
    "name": "Sonny Fodera",
    "slug": "sonny-fodera",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/sonny-fodera.jpg"
  },
  {
    "name": "SOSA",
    "slug": "sosa",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/sosa.jpg"
  },
  {
    "name": "Sven Väth",
    "slug": "sven-vath",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/6e7e7a3d-5e0f-4ed9-b0cc-78c74a1da37e/05f868c6-1dca-437a-9569-f0f827bf03e7.webp"
  },
  {
    "name": "The Magician",
    "slug": "the-magician",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/e54827ee-b87b-4a60-82d3-fd48ca3ff14a/e8290b81-0891-4335-844c-1218de68b1f5.jpg"
  },
  {
    "name": "The Martinez Brothers",
    "slug": "martinez-brothers",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/martinez-brothers.jpg"
  },
  {
    "name": "The Menendez Brothers",
    "slug": "menendez-brothers",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/menendez-brothers.jpg"
  },
  {
    "name": "The Shapeshifters",
    "slug": "the-shapeshifters",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/f843fdf7-c2fe-49ac-821d-d2d1aaa30df8/32f114b4-d385-403b-92cd-5208a28a03ff.jpg"
  },
  {
    "name": "Tita Lau",
    "slug": "tita-lau",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/tita-lau.jpg"
  },
  {
    "name": "Todd Terje",
    "slug": "todd-terje",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/1da75229-5ecd-44bc-9a19-92ad6d62564e/ad23b2af-753e-471f-a666-966022fefce9.jpg"
  },
  {
    "name": "Toman",
    "slug": "toman",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/toman.jpg"
  },
  {
    "name": "Tommy Phillips",
    "slug": "tommy-phillips",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/8c6d9c65-50d0-455d-ba99-41b5823409e3/3695ebc5-4481-4871-9916-954f9c58a2d4.jpeg"
  },
  {
    "name": "Tony Guerra",
    "slug": "tony-guerra",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/f4830957-1969-4c57-b3af-8e6c7e907a54/25732f74-1c28-4f64-83b6-26f40617c16e.jpg"
  },
  {
    "name": "Traumer",
    "slug": "traumer",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/traumer.png"
  },
  {
    "name": "Tripolism",
    "slug": "tripolism",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/1ac9e9e6-f474-4c01-8c87-797f8555b34d/557347c8-8cd1-42cc-aa51-95080a6ade59.jpg"
  },
  {
    "name": "TSHA",
    "slug": "tsha",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/tsha.jpg"
  },
  {
    "name": "Tyla",
    "slug": "tyla",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/349d2b65-cb3d-4f9c-908d-70158f1ae634/05491a57-26c5-4cf7-b42c-a8b741ad7853.jpeg"
  },
  {
    "name": "Vanjee",
    "slug": "vanjee",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/vanjee.jpg"
  },
  {
    "name": "Verso",
    "slug": "verso",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/9e3e1014-aed9-437c-a0c2-a94d15318d24/d5cfa0e6-a21a-413a-b69e-5b5ae97e0b6a.jpg"
  },
  {
    "name": "Vintage Culture",
    "slug": "vintage-culture",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/vintage-culture.jpg"
  },
  {
    "name": "Volkoder",
    "slug": "volkoder",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/13532738-7213-4490-ab08-4ab72065ceb8/7a93bd35-b9ac-4d83-9b4f-ed608ec9a095.jpg"
  },
  {
    "name": "Wade",
    "slug": "wade",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/wade.jpg"
  },
  {
    "name": "Wave Wave",
    "slug": "wave-wave",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/wave-wave.jpg"
  },
  {
    "name": "WhoMadeWho (Hybrid DJ Set)",
    "slug": "whomadewho",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/whomadewho.png"
  },
  {
    "name": "Yugo Sanchez",
    "slug": "yugo-sanchez",
    "image": "https://pacha-media-uploads.s3.us-east-1.amazonaws.com/artists/yugo-sanchez.jpg"
  },
  {
    "name": "Yuksek",
    "slug": "yuksek",
    "image": "https://pacha-production.s3.eu-west-1.amazonaws.com/0e932f1c-9980-425e-bc1a-d678b034b6ce/cef22ad2-1c97-4226-9946-657812a66c45.webp"
  }
]
